//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoring.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("89.32.144.170")]
        public string HOST_NAME {
            get {
                return ((string)(this["HOST_NAME"]));
            }
            set {
                this["HOST_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string USERNAME {
            get {
                return ((string)(this["USERNAME"]));
            }
            set {
                this["USERNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("oki.delamol")]
        public string PASSWORD {
            get {
                return ((string)(this["PASSWORD"]));
            }
            set {
                this["PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ssh-rsa 2048 90:fa:1e:e9:09:40:5e:67:fd:15:e8:63:95:d5:7a:37")]
        public string SSH_HOST_KEY_FINGERPRINT {
            get {
                return ((string)(this["SSH_HOST_KEY_FINGERPRINT"]));
            }
            set {
                this["SSH_HOST_KEY_FINGERPRINT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyyMMdd")]
        public string FILE_NAME_FORMAT {
            get {
                return ((string)(this["FILE_NAME_FORMAT"]));
            }
            set {
                this["FILE_NAME_FORMAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/home/MONITORING/blokade/output")]
        public string FILE_PATH {
            get {
                return ((string)(this["FILE_PATH"]));
            }
            set {
                this["FILE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".csv")]
        public string FILE_EXTENSION {
            get {
                return ((string)(this["FILE_EXTENSION"]));
            }
            set {
                this["FILE_EXTENSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string DB_USERNAME {
            get {
                return ((string)(this["DB_USERNAME"]));
            }
            set {
                this["DB_USERNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0S4m0S4m")]
        public string DB_PASSWORD {
            get {
                return ((string)(this["DB_PASSWORD"]));
            }
            set {
                this["DB_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Monitoring")]
        public string DB_CATALOG {
            get {
                return ((string)(this["DB_CATALOG"]));
            }
            set {
                this["DB_CATALOG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lapitopi")]
        public string DB_SERVER {
            get {
                return ((string)(this["DB_SERVER"]));
            }
            set {
                this["DB_SERVER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MAIL_ADDRESS {
            get {
                return ((string)(this["MAIL_ADDRESS"]));
            }
            set {
                this["MAIL_ADDRESS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MAIL_PASSWORD {
            get {
                return ((string)(this["MAIL_PASSWORD"]));
            }
            set {
                this["MAIL_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Ivan\\Desktop\\Monitoring\\template.xlsx")]
        public string FILE_TEMPLATE_PATH {
            get {
                return ((string)(this["FILE_TEMPLATE_PATH"]));
            }
            set {
                this["FILE_TEMPLATE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Ivan\\Desktop\\Monitoring\\Result")]
        public string LOCAL_RESULT_DIRECTORY {
            get {
                return ((string)(this["LOCAL_RESULT_DIRECTORY"]));
            }
            set {
                this["LOCAL_RESULT_DIRECTORY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Ivan\\Desktop\\Monitoring\\skinuto")]
        public string LOCAL_CSV_DIRECTORY {
            get {
                return ((string)(this["LOCAL_CSV_DIRECTORY"]));
            }
            set {
                this["LOCAL_CSV_DIRECTORY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public string INTERVAL_INTERVAL {
            get {
                return ((string)(this["INTERVAL_INTERVAL"]));
            }
            set {
                this["INTERVAL_INTERVAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("06")]
        public string INTERVAL_DOWNLOAD_TIME {
            get {
                return ((string)(this["INTERVAL_DOWNLOAD_TIME"]));
            }
            set {
                this["INTERVAL_DOWNLOAD_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Ivan\\Desktop\\Monitoring\\template_aks.xlsx")]
        public string FILE_TEMPLATE2_PATH {
            get {
                return ((string)(this["FILE_TEMPLATE2_PATH"]));
            }
            set {
                this["FILE_TEMPLATE2_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Ivan\\Desktop\\Monitoring\\template_sa_statusom.xlsx")]
        public string FILE_TEMPLATE3_PATH {
            get {
                return ((string)(this["FILE_TEMPLATE3_PATH"]));
            }
            set {
                this["FILE_TEMPLATE3_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Ivan\\Desktop\\Monitoring\\template4.xlsm")]
        public string FILE_TEMPLATE4_PATH {
            get {
                return ((string)(this["FILE_TEMPLATE4_PATH"]));
            }
            set {
                this["FILE_TEMPLATE4_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Ivan\\Desktop\\Monitoring\\template5.xlsm")]
        public string FILE_TEMPLATE5_PATH {
            get {
                return ((string)(this["FILE_TEMPLATE5_PATH"]));
            }
            set {
                this["FILE_TEMPLATE5_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Ivan\\Desktop\\Monitoring\\template6.xlsm")]
        public string FILE_TEMPLATE6_PATH {
            get {
                return ((string)(this["FILE_TEMPLATE6_PATH"]));
            }
            set {
                this["FILE_TEMPLATE6_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Ivan\\Desktop\\Monitoring\\template7.xlsm")]
        public string FILE_TEMPLATE7_PATH {
            get {
                return ((string)(this["FILE_TEMPLATE7_PATH"]));
            }
            set {
                this["FILE_TEMPLATE7_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Ivan\\Desktop\\Monitoring\\template9.xlsx")]
        public string FILE_TEMPLATE9_PATH {
            get {
                return ((string)(this["FILE_TEMPLATE9_PATH"]));
            }
            set {
                this["FILE_TEMPLATE9_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Ivan\\Desktop\\Monitoring\\template10.xlsx")]
        public string FILE_TEMPLATE10_PATH {
            get {
                return ((string)(this["FILE_TEMPLATE10_PATH"]));
            }
            set {
                this["FILE_TEMPLATE10_PATH"] = value;
            }
        }
    }
}
